### PR TITLE
Added camera resolutions into settings dialog

### PR DESCRIPTION
**Pull request by hekkup**
- created CameraInfo class to get resolutions + tested class (not well though)
- added CameraInfo into Camera class
- showing resolution combo box in settings dialog, removed earlier width and height fields
- not possible to give resolution manually anymore except in config file
- aspect ratio check remains here and there but could be removed
- not tested whether querying works with more web camera brands (I used an old Logitech cam)

### CODE REVIEW

**Comment by UFOID** [comment]
How long does it take for you to query the supported resolutions on start up? When I run it on Windows it takes a few minutes to query..:(

**Comment by hekkup** [comment]
In Linux, going through the complete list of resolutions takes under 100 ms with and old Logitech webcam. In the latest commit 20db5baabd0e25dfd8525d7cb48657b1acbd43b1 I have added a performance measurement in CameraInfo unit test (test/testCameraInfo). Also for Windows I reduced the number of resolutions down to ten. Could you please run the test and see how long it takes to query those 10 resolutions?

Slow querying might also be because of the webcam itself. What brand and model you have? Would it be possible to test it in Linux?

Poor query performance means there should be manual input for resolution setting. In that case there might be a verification button to check the given resolution. Querying is possible but there should be a button for that, and a warning message it could take many minutes.

**Comment by UFOID** [comment]
I tested it a bit more using my main webcam the Logitech c920 and unfortunately I don't have good news.
Running the test takes about 3 seconds for the querying to finish. However, when launching the program as it is in this pull request it takes about 3 minutes to launch. I can see in the console that each resolution check takes about 3-6 seconds. It increases as the resolution goes up.
Now here is the bad news that I didn’t realize before: After completing all the checks the program launches showing a black image as the webcam frame. In fact any program that uses the webcam (skype, Logitech software) will now only show a black frame. Somehow the querying “broke” the webcam. The only solution is for me to re-connect the device and launch the Logitech software. Now the webcam works again. Next time I will launch the Detector with the querying it will break again.

I am not sure if this happens due to querying the higher resolution. It did show me in the console that some resolutions higher than 1080p where determined as OK when the webcam only supports 1080p. Even if we can fix the breaking of the webcam, the time it takes for the querying at start up is still problematic.
I will check some other webcam devices I have later this evening. I will also try to set up my Linux environment again. For now I was using Windows 7

**Comment by UFOID** [comment]
The difference between the test and the Detector performance is that the test uses webcam index 0 by default (which is ManyCam.com software for me) while I am using index 1 for my Logitech in the Detector

**Comment by UFOID** [comment]
Some more testing on Windows 7.
I think it has to do with the amount of resolution checks. It doesn't matter if I only check the small ones or only the large ones. If I reduce the list to about half of what it currently is it will work. It seems random as in one list will work one time (taking a few minutes to load) but the next time the same list will cause the webcam to "break". I have never experienced my webcam just displaying a black frame before. Funny/Scary thing: If the "broken" webcam is connected to the PC at start up it will cause the system to freeze at the BIOS splash screen..

I also tested it with my PS3 eye cam and the querying shows "No support for resolution x x y-- got  0 x 0 instead" for each resolution (640×480 works fine in the Detector).

This would have been a very nice solution but it seems like it can't be implemented to work with any webcam device. I think forcing to user to check the resolution of his device and entering it manually is the only way to go:(

**Comment by hekkup** [comment]
It might be a bug in OpenCV, too. Maybe I'll file a bug over there (https://github.com/Itseez/opencv).

It's possible to try testing VideoCapture behaviour with different backends. I added such a test in the unit test of CameraInfo in ca562a4c44e3612639e1c1704b339dac4d6f8fcc. There's a list of backends over here: http://docs.opencv.org/master/dd/de7/group__videoio.html

But anyway, I will start falling back to the original method of manually entering the cam resolution. The drop-down list can be used in Linux (well, can it?? :) should test with Logitech c920) but need to think how the UI will look good still.

**Comment by UFOID** [comment]
I will set up my linux environment on the weekend and check my devices again. I should probably also test it with OpenCV 3.1. I am using 3.0 right now (looking at the changelog I don't see any cv::VideoCapture changes in 3.1)

**Comment by hekkup** [comment]
Filed an OpenCV bug report at https://github.com/Itseez/opencv/issues/6505

**Comment by UFOID** [comment]
Interesting. I just tested it on Ubuntu and querying my Logitech takes about a second. Not a few minutes like on Windows. It still shows 2304x1296 and higher to be acceptable. The model only supports up to 1080p. Anything higher causes a framerate of less than 1 frame per second.
Maybe we should remove anything higher than 1080p in the query checking list. I can see users running the check and simply selecting the highest available option which will then cause problems. Most webcams don’t support anything more than 1080p anyway. If someone has a setup that works with a higher resolution than 1080p (and a system to handle that kind of resolution without lag!) he can always enter the desired resolution manually. What do you think?

I like the resolution query dialog. Well done

**Comment by UFOID** [comment]
I just noticed that some of the options that you get from the querying check don’t go along with the current aspect ratio check. We either have to remove the aspect ratio check or only use it when the user enters the resolution manually.

**Comment by hekkup** [comment]
In general I prefer more generic solutions, so I wouldn't like to remove resolutions higher than 1080p. Even if most cameras support 1080p now, how about in 5-10 years? One resolution I saw in a cheap basic camera is 1600x1200. So, I'd rather prefer adding a warning text to the query dialog recommending the user to choose only vendor-supported resolutions.

I think your camera probably entered still photo mode instead of video mode. Many cameras have better resolution available in still photo modes, and those modes are not fast enough for videos. Maybe cv::VideoCapture does its best thinking it is providing a video while it's really just taking photos as fast as the camera allows.

I can calculate the aspect ratios from common resolutions and add the new ones to the list of accepted ratios. I agree the manually entered resolutions should be checked.

Maybe there should be a "force the manually entered resolution with strange aspect ratio" feature just in case user really wants to use some unknown camera? Query finds unlisted resolutions and adds them to the list but it might happen that querying doesn't work for that particular camera/OS.

**Comment by UFOID** [comment]
> In general I prefer more generic solutions, so I wouldn't like to remove resolutions higher than 1080p

Ok, I agree

> cv::VideoCapture does its best thinking it is providing a video while it's really just taking photos as fast as the camera allows.

I think you are right with that.

> Maybe there should be a "force the manually entered resolution with strange aspect ratio" feature just in case user really wants to use some unknown camera?

This would probably require an extra checkbox and I feel like this is a bit of an overkill. I don't see any case where the manually entered resolution doesn't fit any of the aspect rations in the (already huge) common resolution list. Certainly the webcam device doesn't require that resolution/aspect ration and I don't see why the user would want to force something that exotic.

Please remove the line `m_commonResolutions << QSize(2304, 1296);` from  ce6ab43 . I meant to say 2304 × 1728 which is already there

**Comment by hekkup** [comment]
Ok, I got an idea: how about if we add "disableCameraAspectRatioCheck" config variable into the settings file but don't have anything for it in the settings dialog? Just like disable application update check setting. This would be mostly for developers and hackers who might experiment anything exotic or even self-made (with Raspberry Pi and Arduinos etc. it is fully possible). That way we could have most flexibility while keeping the default operation safe.

Edit: here's one example of a DIY camera:
http://www.cloudynights.com/topic/497530-diy-astro-ccd-16-bit-color-6mpx-camera/

**Comment by UFOID** [comment]
That sounds ideal!

**Pull request merged**
