### PR TITLE
Basic CLI version started

### PR DESCRIPTION
**Pull request by hekkup**
Fixes UFOID/UFO-Detector#29.

Created DataManager class into the detector engine and moved a lot of data handling from MainWindow into it.

### CODE REVIEW

**Comment by UFOID** [comment]
I see you are still updating the code. Please let me know once you think it is ready for me to check and merge

**Comment by hekkup** [comment]
Should be alright now. Tests are not complete, though they weren't before, either.

**Comment by hekkup** [comment]
App version number is now on engine side in config.h. It's still at 0.7.0 in my master branch.

**Comment by UFOID** [comment]
Thanks for this. I won't be able to check it until the 20th.

**Comment by UFOID** [comment]
works like a charm! thanks

**Pull request merged**
