### PR TITLE
Added layout to main view and made webcam check more flexible

### PR DESCRIPTION
**Pull request by hekkup**
... plus small bug fixing.
I'm not sure if this more flexible webcam check is okay. I played with different sizes and it seemed more or less ok.

### CODE REVIEW

**Comment by UFOID** [comment]
Please include the check that the set webcam resolution has a "real" aspect ratio. If user sets the resolution to something incorrect it can lead to crash at startup with some webcam devices.

Also please set the "Clear Messages" and "Upload Images" layout the same as the "Detect" and "Stop" button. This is how it looks for me on Windows:
untitled

**Comment by hekkup** [comment]
As for webcam resolution, I think the best way would be to have a list of available modes. Then the user could just select any mode. Here's how it can be done: http://stackoverflow.com/questions/18458422/query-maximum-resolution-in-opencv
Do you know if querying webcam resolution could cause crash in those problematic webcam models? Querying doesn't involve taking pictures with the cam, just querying properties of camera.

Ok for the buttons. I would like to put the Clear messages and Upload images buttons together with the other buttons eventually because now the buttons are scattered.

**Comment by UFOID** [comment]
A drop down list with the common resolution would be a [huge ](https://en.wikipedia.org/wiki/List_of_common_resolutions)list

I didn't have much success the last time I tried to use VideoCapture::get to find out the preferred/max web cam resolution. I will investigate again.
For now please just use the current check to see if the selected resolution fits one of the three common aspect ratios.

I quickly changed the button arrangement (fixed, no layout). Thoughts?
untitled

**Comment by hekkup** [comment]
Yeah, of course it's not possible to include all resolutions, but I meant only supported resolutions for the currently active camera. I'll investigate, too, how to query the supported resolutions. Maybe for this pull request the quickest solution would be to fall back to the aspect ratio check.

The button order looks better now. I assume Start button will change to Stop button once detection is running.

**Comment by hekkup** [comment]
Old Logitech web cam has aspect ratio 1.22 available so I included it.

The main window buttons are the old buttons just reordered and reshaped a bit.

**Pull request merged**
